name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.17' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Lint
      uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.2"
        install-go: false
        cache-key: ${{ matrix.go }}
    - name: Test
      run: go test -cover -race ./...
