name: Continuous Integration
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with: 
          go-version: '1.14'

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
          golangci-lint run

  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with: 
          go-version: '1.14'

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test
        run: go test -race -cover ./...
